### ISSUE TITLE
Allow running checks without running composer install

### ISSUE THREAD

**Issue by bdsl** [Roave/you-are-using-it-wrong#17]
Indirect users of this package may want to know whether they are using libraries wrong, without having run `composer install`. Arguably they should just initialise Psalm in their own project, but if they don't want to do that, we could help them by outputting something like the following during composer install:

```
roave/you-are-using-it-wrong: Authors of the following package(s): My\AwesomeLibrary
have requested that references to them are type-checked...

checking strictly type-checked packages...
Scanning files...
Analyzing files...

------------------------------
No errors found!
------------------------------
To re-run these checks, use:
    ./vendor/bin/you-are-using-it-wrong

```

Running the binary would be similar to calling [Hook::runTypeChecks](https://github.com/Roave/you-are-using-it-wrong/blob/1f6b6e112a94ace751d13fe5f1aeb96f18c8acc7/src/Hook.php#L50).

**Comment by xepozz** [comment]
May to use `pre-autoload-dump` instead of `post-update-cmd` and `post-install-cmd`
(https://getcomposer.org/doc/articles/scripts.md#command-events)

**Comment by Ocramius** [comment]
`pre-autoload-dump` is probably too early: no autoloader then, which can lead to a lot of funky business :|

**Comment by Ocramius** [comment]
Closing here: the checks can effectively be run by re-running `composer install`, which is an idempotent operation when running on a stable system.
