### ISSUE TITLE
Remove psalm dependency from composer.json

### ISSUE THREAD

**Issue by bdsl** [Roave/you-are-using-it-wrong#2]
(At time of writing master branch is almost empty, so this issue relates to the code in feature/enforce-type-safety-in-dependants . Issue started as comment at https://github.com/Roave/you-are-using-it-wrong/pull/1/files#r280975529 )

composer.json includes `"vimeo/psalm": "dev-master"` in the `require` section. This means that psalm and all its dependencies will be included in all installs of any project that directly or indirectly requires this, even if they opt-out by creating a psalm.xml file. More importantly it means that this can't be installed if the root project or any other dependency specifies a conflicting version of Psalm or of any of the [libraries required by psalm](https://github.com/vimeo/psalm/blob/master/composer.json#L12).

I think this issue could be solved by downloading psalm separately and probably running it in a separate process. Maybe as a .phar, or maybe like how [Symfony's PHPUnit bridge downloads PHPUnit to a .phpunit directory](https://github.com/symfony/phpunit-bridge/blob/master/bin/simple-phpunit#L75).

See Sebastian Bergmann's [thread on why he disprefers requiring tools like Psalm (and even PHPUnit) via composer](https://twitter.com/s_bergmann/status/999635212723212288).

**Comment by Ocramius** [comment]
Just tossing in my opinion on https://twitter.com/s_bergmann/status/999635212723212288 (the thread about why not `require-dev`): composer is an extremely stable delivery mechanism for packages, and designing an alternate mechanism for that is very problematic from a security and maintenance perspective. Downloading unsigned code is not something I'd touch even with a stick from afar.

I'd rather keep an explicit `require` and have the SAT of composer itself deal with upgrades as it sees fit for now and until it becomes a pressing issue.

In addition to that, `phar` distributions are unsuited for usage until php-scoper reaches full maturity: until then, the issues raised by sharing symbols between process memory and phar are too big.

**Comment by Ocramius** [comment]
After re-evaluating this, marking it as "won't fix".

I already maintain multiple plugins that are based on the excellent ability of @composer to provide dependency resolution, download and installation from upstream sources, so this kind of concern should bubble up into @composer instead, if it is a concern at all.

The best I can do here is to keep bumping dependency versions as they come up.

**Comment by bdsl** [comment]
I just noticed the existence of [psalm/phar](https://github.com/psalm/phar). Perhaps using that instead of [vimeo/psalm](https://github.com/vimeo/psalm) would be a good option.

**Comment by Ocramius** [comment]
If that has scoped dependencies, sure 👍

**Comment by bdsl** [comment]
Yes it does:

![Screenshot from 2019-06-01 17-09-09](https://user-images.githubusercontent.com/159481/58750932-1260c680-8490-11e9-8d79-259b93ef3cfb.png)

The phar is built by the script at https://github.com/vimeo/psalm/blob/dc5a5bcd9dab1a67fdb057a80086f8259e3629aa/bin/build-phar.sh

**Comment by Ocramius** [comment]
Hmm, just realised that I strictly depend on the classes in psalm in this codebase, so this approach won't work either, unless this package is also served as scoped phar.

**Comment by bdsl** [comment]
Right, you'd have to know the namespace inside the phar, which makes things difficult. When I first raised this issue I didn't realise that `you-are-using-it-wrong` uses psalm in a way that's different to just running the psalm executable.

Probably one of the biggest downsides of having the psalm dependency is that it will conflict with `symfony/console` 2.8, which is no longer maintained but is receiving security support until November.

**Comment by Ocramius** [comment]
I'm not too worried about support for older packages: more worrisome is
support in the future, upgrades, etc.

**Comment by bdsl** [comment]
An other option might be to change the interface of psalm itself, so that it can be passed the necessary options to run as needed here through command line arguments and/or a temp psalm.xml config file.

**Comment by Ocramius** [comment]
Possibly, yes: it would need to be a huge JSON of filtered namespaces
though.
