### ISSUE TITLE
No errors shown when running composer, only error code

### ISSUE THREAD

**Issue by simPod** [Roave/you-are-using-it-wrong#62]
When running `composer install`, there are no errors shown for my package. Only status code is set to 255:

```
...
roave/you-are-using-it-wrong: checking strictly type-checked packages...
roave/you-are-using-it-wrong: following package usages will be checked:
 - my/library
 - - My\LibraryNs\
$ echo $status
255
```
Am I doing something wrong? My library is using v1.3 of this.

**Comment by Ocramius** [comment]
What's the output with `-vvv`?

**Comment by simPod** [comment]
Identical to the one above 🤔 

If it's the first time you encountered this I guess I'll give debugger a shot.

**Comment by Ocramius** [comment]
Can you check if dev-master makes any difference?

**Comment by simPod** [comment]
Ee, same unfortunately.

**Comment by simPod** [comment]
It dies on loading `Symfony\Component\Console\Style\SymfonyStyle` (ReflectionClass). Don't know why yet.

**Comment by simPod** [comment]
Ok, error reporting is not enabled. When force enable it showed the error:

> Fatal error: Declaration of Symfony\Component\Console\Style\OutputStyle::write($messages, bool $newline = false, int $type = self::OUTPUT_NORMAL) must be compatible with Symfony\Component\Console\Output\OutputInterface::write($messages, $newline = false, $options = 0)

**Comment by simPod** [comment]
Cool, I was lazy enough not to write what I have enabled to show the error. Was not this `php -d display_errors=1`.
