### ISSUE TITLE
usage in github actions requires composer-plugin-api[2.0.0]

### ISSUE THREAD

**Issue by marcosh** [Roave/you-are-using-it-wrong#87]
`composer install` fails saying that

```
Problem 1
    - roave/you-are-using-it-wrong is locked to version 1.4.0 and an update of this package was not requested.
    - roave/you-are-using-it-wrong 1.4.0 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
```

see https://github.com/marcosh/lamphpda/runs/882257039?check_suite_focus=true

is it enough to increase the requirement in `composer.json`?

**Comment by Ocramius** [comment]
If you run `composer/composer:^2` in CLI, then `composer-plugin-api:2.0.0` is present at runtime.

The interface changed in `composer-plugin-api:2.0.0`, so some adjustments are needed in https://github.com/Roave/you-are-using-it-wrong/blob/d3f68b24600bd1c3b6439d29cd519f9d40e5f353/src/Hook.php#L29

I suggest bumping and upgrading the implementation to support the new interface.

An example patch that does this can be seen at https://github.com/Ocramius/PackageVersions/pull/133

**Comment by Ocramius** [comment]
Moving this to `1.6.0`.

Will probably bump to `composer-plugin-api:^2` there, so that the interface is stable.

See also https://github.com/Roave/you-are-using-it-wrong/pull/92/commits/3dca58b4c6e071eb515a34cee28f2ff0821486a0 (to be reverted when working on this)

**Comment by Ocramius** [comment]
Done in #93
