### ISSUE TITLE
Support PHPStan and Phan, too

### ISSUE THREAD

**Issue by Aerendir** [Roave/you-are-using-it-wrong#9]
Other than Psalm, there are also PHPStan and Phan, two static analyzers widely used.

Do they deserve some support as Psalm has?

Currently, I don't use Psalm, but use both PHPStan and Phan (Psalm is the next one in the todo list): this library may cause a longer install time in my apps that use the libraries in which I will implement this package (or that use other libraries that use this one).

Supporting the other two static analyzers will avoid this side effect.

**Comment by Ocramius** [comment]
> Do they deserve some support as Psalm has?

Not possible at this time.

The current problem with @phpstan right now is that it is hard to communicate very trivial types such as `Repository<User>`, and it requires extensions to do that. Until there is such feature in place, it is not really possible for upstream libraries to include `roave/you-are-using-it-wrong` and also type-check in consumers.
