### ISSUE TITLE
Getting exception Package "vimeo/psalm" is not installed

### ISSUE THREAD

**Issue by frankvanhest** [Roave/you-are-using-it-wrong#95]
Hi there,

Today I was trying to install this package, but during I got the following error:

roave/you-are-using-it-wrong: checking strictly type-checked packages...
 roave/you-are-using-it-wrong: following package usages will be checked:
 
 
   [OutOfBoundsException]
   Package "vimeo/psalm" is not installed
 
I'm using composer 2.0.6 and version 1.7.0 of this repo.

Can you help me with this issue? If you need more information, let me know.

Thanks you in advance.

Cheers, Frank

**Comment by Ocramius** [comment]
Sounds (potentially) like composer v2 does not yet have all package information loaded when running this particular plugin :thinking: 

The code being executed is https://github.com/Roave/you-are-using-it-wrong/blob/97214839a5b739ed28630db178b0d56ed33a1982/src/Hook.php#L83-L89

Overall, I'd suggest trying an upgrade to `ocramius/package-versions:^2` in here, although unsure if `vimeo/psalm` is compatible with that.

**Comment by frankvanhest** [comment]
Thanks for the quick reply. I've tried using your suggestion, but I run into a conflict. 
```
Problem 1
     - ocramius/package-versions 2.2.0 requires php ~8.0.0 -> your php version (7.4.9) does not satisfy that requirement.
     - Root composer.json requires roave/you-are-using-it-wrong ^1.7 -> satisfiable by roave/you-are-using-it-wrong[1.7.0].
     - Conclusion: don't install ocramius/package-versions 2.1.0 (conflict analysis result)
     - roave/you-are-using-it-wrong 1.7.0 requires ocramius/package-versions ^1.9.0 -> satisfiable by composer/package-versions-deprecated[1.10.99, 1.10.99.1, 1.11.99].
     - Only one of these can be installed: composer/package-versions-deprecated[1.8.0, ..., 1.11.99], ocramius/package-versions[2.0.0, 2.1.0, 2.2.0]. composer/package-versions-deprecated replaces ocramius/package-versions and thus cannot coexist with it.
     - Root composer.json requires ocramius/package-versions ^2 -> satisfiable by ocramius/package-versions[2.0.0, 2.1.0, 2.2.0].
```
 
This is my composer.json required section:
```
"require": {
    "php": "^7.4",
    "beberlei/assert": "^v3.2",
    "myclabs/php-enum": "^1.7",
    "ocramius/package-versions": "^2",
    "ramsey/uuid": "^4.1",
    "roave/dont": "^1",
    "roave/you-are-using-it-wrong": "^1.7",
    "symfony/dependency-injection": "^v5.1"
  },
  "require-dev": {
    "behat/behat": "^v3.8",
    "phpstan/extension-installer": "^1.0",
    "phpunit/phpunit": "^9",
    "roave/behat-psr11extension": "^1.2",
    "roave/security-advisories": "dev-latest"
  },
```

Did I miss something or is it best to keep using composer v1 for now?

**Comment by Ocramius** [comment]
I would probably first report it upstream in `composer/package-versions-deprecated`, which seems to be used by your stack.

**Comment by frankvanhest** [comment]
It seems that vimeo/psalm is using `composer/package-versions-deprecated`. 
I'll create an issue in `composer/package-versions-deprecated`.

Thanks for your help!

**Comment by Seldaek** [comment]
https://github.com/composer/composer/issues/9457 should be fixed now, it was a composer issue.

**Comment by frankvanhest** [comment]
@Seldaek Again thank you for your efforts. @Ocramius with the current snapshot version of composer I can use this package without any problems.
